---
title: "Homework 3"
author: Na Yun Cho
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
library(patchwork)
data("ny_noaa")

knitr::opts_chunk$set(
  fig.width = 8,
  fig.asp = 0.6,
  fig.height = 0.6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
```



# Problem 2

```{r}
accel_df = read.csv("./data/accel_data.csv") %>%
  janitor::clean_names() %>%
  pivot_longer(
    activity_1:activity_1440, 
    names_to = "minute",
    names_prefix = "activity_", 
    values_to = "activity_count"
  ) %>%
  mutate(
    minute = as.numeric(minute),
    day = factor(day),
    day = fct_relevel(day, "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"),
    weekend = as.numeric(day %in% c("Saturday", "Sunday")),
    weekend = recode(weekend, '1' = "weekend", '0' = "weekday"))

```

```{r}
accel_df %>% 
  group_by(day , week) %>%
  summarize(act_total = sum(activity_count)) %>%
  pivot_wider(
    names_from = day, 
    values_from = act_total)
  
```

```{r}
accel_df %>%
  ggplot(aes(x= minute, y= activity_count, group = day_id, color = day)) +
  geom_line(alpha =0.2) + 
  geom_smooth(aes(group = day), se = FALSE)
```

# Problem 3

```{r}
ny_noaa_df =
  ny_noaa %>% 
  separate(date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin),
    tmax = tmax/10,
    tmin = tmin/10,
    prcp = prcp/10
  )

ny_noaa_df %>%
  count(snow) %>%
  arrange(desc(n))
  
```

```{r}
ny_noaa_df %>% 
 filter(month %in% c("01", "07")) %>%
  group_by(id, year, month) %>%
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)) %>%
  ggplot(aes(x = year, y = mean_tmax, group = id)) + 
  geom_point(alpha = 0.5, size = 0.5) +
  geom_path() +
  facet_grid(.~month) +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.5, hjust = 1))
  
```


```{r}
tmax_vs_tmin = 
  ny_noaa_df %>%
  ggplot(aes(x = tmax, y = tmin)) + 
  geom_hex()

snowfall_dist = 
  ny_noaa_df %>% 
  filter(snow < 100) %>%
  filter(snow > 0) %>%
  ggplot(aes(x = year, y = snow)) + geom_violin(alpha = 0.5) + 
  theme(axis.text.x = element_text(angle = 270, vjust = 0.5, hjust = 1))

tmax_vs_tmin + snowfall_dist
```

